name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/environment39.yml

      - name: Install
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest -v --cov
