name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/environment39.yaml
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: gradle
        uses: gradle/gradle-build-actions@v2

      - name: build dockerfile
        shell: bash -l {0}
        run: |
          git clone https://github.com/tabular-io/iceberg-rest-image
          cd iceberg-rest-image
          gradle build
          docker build -t ice .
          cd ..

      - name: Install
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest -v --cov
