name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/environment39.yaml
      - name: Install and test
        shell: bash -l {0}
        run: |
          pip install -e .
          docker pull mdurant/ice:1
          pytest -v --cov -s --tb=no
