name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: test_env
          environment-file: ci/environment39.yml
      - name: Install
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest -v --cov
